In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/data.csv")

df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df = df.drop(["id", "Unnamed: 32"], axis=1)

df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [ ]:
df["diagnosis"] = df["diagnosis"].map({"M":1, "B":0})

df.head()

   diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0          1        17.99  ...          0.4601                  0.11890
1          1        20.57  ...          0.2750                  0.08902
2          1        19.69  ...          0.3613                  0.08758
3          1        11.42  ...          0.6638                  0.17300
4          1        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [ ]:
x = df.drop(["diagnosis"], axis=1)
y = df["diagnosis"]

x_train, x_test,  y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=57)

In [ ]:
rdf = RandomForestClassifier(
    n_estimators=500, 
    oob_score=True,
    n_jobs=-1,
    random_state=57
)

In [ ]:
rdf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=-1, oob_score=True, random_state=57, verbose=0,
                       warm_start=False)

In [ ]:
rdf.score(x_test, y_test)

0.9824561403508771

In [ ]:
y_pred = rdf.predict(x_test)

In [ ]:
metrics.accuracy_score(y_pred, y_test)

0.9824561403508771